#!/usr/bin/env bash

set -e

target_dir=$HOME/Pictures
wall=$HOME/Pictures/island-night.png

mkdir -p "$target_dir" && install ./*.{jpg,png,jpeg,gif,heic} "$target_dir" && install "$wall" "$HOME"/Pictures/wall.png
